//
// APlayer.hh for Bomberman in /home/polydo_s/rendu/Bomberman/includes
//
// Made by polydo_s
// Login   <polydo_s@epitech.net>
//
// Started on  Tue May  5 19:56:12 2015 polydo_s
// Last update Fri May 15 23:23:45 2015 polydo_s
//

#ifndef PLAYER_HH
#define PLAYER_HH

/**
 * @class APlayer
 * @brief A player
 *
 * A Aplayer can move, die, get bonuses
 * and plant bombs.
 * Each of them has a unique ID.
 *
 * @author Swann Polydor (polydo_s)
 * @version 0.1
 * @bug No known bugs.

 * @date May 4, 2015
 */

#include "ACharacter.hh"

class	APlayer : public ACharacter {

protected:
  unsigned int	_id; //!< A unique generated ID for each player

public:
  /**
   * Construct a new player
   * The unique ID is generated by itself
   */
  APlayer(float x, float y, ACharacter::eOrientation orientation);

public:
  virtual void	draw() const;

public:
  /**
   * Get the character's ID
   */
  unsigned int	getId() const;

  const std::string	ToString() const;
};

#endif
