//
// Player.hh for Bomberman in /home/polydo_s/rendu/Bomberman/includes
//
// Made by polydo_s
// Login   <polydo_s@epitech.net>
//
// Started on  Sun May  3 19:10:14 2015 polydo_s
// Last update Mon May  4 00:49:37 2015 polydo_s
//

#ifndef PLAYER_HH
#define PLAYER_HH

/**
 * @class Player
 * @brief Class representing a player
 *
 * A player can be a human or an IA,
 * they both can perform the exact same
 * actions and can be distinguished by
 * the _bot attribute
 *
 * @author Swann Polydor (polydo_s)
 * @version 0.1
 * @bug No known bugs.

 * @date May 4, 2015
 */
class	Player : public ACharacter {

protected:
  unsigned int	_id; //!< A unique generated ID for each player
  bool		_bot; //!< Make it playable or AI controlled

public:

  /**
   * Construct a new player
   * The unique ID is generated by itself
   *
   * @param bot playable or AI controlled
   */
  Player(bool bot);

public:
  /**
   * Draw a character
   */
  void	draw() const;

public:
  /**
   * Get the character's ID
   */
  unsigned int	getId() const;

  /**
   * Get the character's nature
   */
  bool		isBot() const;
};

#endif
